version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan-approval-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - loan-network
    depends_on:
      - mlflow
    restart: unless-stopped
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --workers 4

  # MLflow Service
  mlflow:
    image: python:3.9-slim
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    working_dir: /mlruns
    networks:
      - loan-network
    command: >
      sh -c "pip install mlflow boto3 &&
             mlflow server 
             --host 0.0.0.0 
             --port 5000 
             --backend-store-uri sqlite:///mlflow.db 
             --default-artifact-root /mlruns"
    restart: unless-stopped

  # PostgreSQL for Airflow (optional)
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - loan-network
    restart: unless-stopped

  # Airflow Webserver (optional)
  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - .:/opt/airflow/dags/loan_approval_system
    ports:
      - "8080:8080"
    networks:
      - loan-network
    command: webserver
    restart: unless-stopped

  # Airflow Scheduler (optional)
  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - .:/opt/airflow/dags/loan_approval_system
    networks:
      - loan-network
    command: scheduler
    restart: unless-stopped

networks:
  loan-network:
    driver: bridge

volumes:
  postgres-db-volume: