[project]
name = "credit-score"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pydantic>=2.11.10",
    "scikit-learn>=1.7.2",
    "shap>=0.48.0",
    "xgboost>=3.0.5",
]
